### ISSUE TITLE
Upgrade to 4.0.0

### ISSUE THREAD

**Issue by dbtek** [mw222rs/choo-firebase#1]
Hi, thanks for providing this. It's very helpful.

I started to upgrade my app to choo 4. I thought older effects with state, data param ordering should work, but it did not.

```js
effects: {
    attemptLogin: (state, data, send, done) => {
      send('auth:setPending', true, done)
      const cred = firebase.auth.EmailAuthProvider.credential(data.email, data.password)
      auth.signInWithCredential(cred)
        .then(res => {
          send('notify:info', { message: 'Successfully signed in' }, done)
          send('auth:setPending', false, done)
        })
        .catch(error => {
          send('notify:error', { message: error.message }, done)
          send('auth:setPending', false, done)
          send('auth:logout', done)
        })
    },
  ...
}
```

Calling this effect starts an infinite loop. It keeps running endlessly. What am I doing wrong?
Thanks in advance.

**Comment by dbtek** [comment]
Ps. I also tried removing done param from repeating sends; and chaining sends in callback functions.

**Comment by fyrkant** [comment]
Hi! I'll try to get to updating the app to v4 as soon as possible, just haven't had time to get into it yet.

**Comment by fyrkant** [comment]
The app is now updated to choo v4!

**Comment by dbtek** [comment]
Thanks @fyrkant.
